export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard:read",
  USERS_MANAGE: "users:manage",
  USERS_READ: "users:read",
  ROLES_MANAGE: "roles:manage",
  PROPERTIES_READ: "properties:read",
  PROPERTIES_MANAGE: "properties:manage",
  PG_MANAGE: "pg:manage",
  TENANTS_READ: "tenants:read",
  TENANTS_MANAGE: "tenants:manage",
  AGREEMENTS_READ: "agreements:read",
  AGREEMENTS_MANAGE: "agreements:manage",
  RENT_READ: "rent:read",
  RENT_MANAGE: "rent:manage",
  BILLS_READ: "bills:read",
  BILLS_MANAGE: "bills:manage",
  PAYMENTS_READ: "payments:read",
  PAYMENTS_CREATE: "payments:create",
  PAYMENTS_VERIFY: "payments:verify",
  RECEIPTS_READ: "receipts:read",
  REPORTS_READ: "reports:read",
  NOTIFICATIONS_READ: "notifications:read",
  NOTIFICATIONS_MANAGE: "notifications:manage",
  SETTINGS_MANAGE: "settings:manage",
  AUDIT_READ: "audit:read",
  MAINTENANCE_MANAGE: "maintenance:manage",
  EXPENSES_MANAGE: "expenses:manage",
} as const;

export type PermissionValue = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
